"""
Prism v2 — PermissionRequest ORM model (DOC-01 v4 §4.2 — 执行恢复域, v4 新增)

Persists Harness permission-ask requests for audit and timeout cleanup.
The real-time channel uses Redis BLPOP; this table is the durable record.

Indexes:
  - (run_id, status)
  - (status, timeout_at)
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, generate_uuid

if TYPE_CHECKING:
    from app.models.run import Run
    from app.models.user import User


class PermissionRequest(Base):
    """
    permission_requests table — DOC-01 v4 §4.2 (v4 新增)

    ``request_id`` is generated by the subprocess (UUID4 string) and used
    as the Redis BLPOP key suffix.

    Lifecycle:
      1. Subprocess inserts row with status='pending'.
      2. Backend receives user decision via POST /sessions/{id}/permission-answer.
      3. Backend RPUSHes to Redis (subprocess returns from BLPOP).
      4. Backend UPDATEs this row to status='allow'|'deny'.
      5. Cleanup job transitions timed-out rows to status='timeout'.
    """

    __tablename__ = "permission_requests"

    __table_args__ = (
        Index("ix_permission_requests_run_status", "run_id", "status"),
        Index("ix_permission_requests_status_timeout", "status", "timeout_at"),
    )

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=generate_uuid
    )
    request_id: Mapped[str] = mapped_column(
        String(36), unique=True, nullable=False
    )
    run_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("users.id"),
        nullable=False,
    )
    tool_name: Mapped[str] = mapped_column(String(100), nullable=False)
    tool_input: Mapped[dict] = mapped_column(JSONB, nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending"
    )
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    answered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    timeout_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    # Relationships
    run: Mapped["Run"] = relationship("Run", back_populates="permission_requests")
    user: Mapped["User"] = relationship("User", foreign_keys=[user_id])
